# Generated by Django 5.2.4 on 2025-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='image_anime')),
                ('nome_personagem', models.CharField(max_length=100)),
                ('anime', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
