# Generated by Django 5.2.4 on 2025-07-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconhecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsao',
            name='probabilidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
